const prof = [
  "Engenheiro de Software",
  "Médico",
  "Advogado",
  "Professor",
  "Designer Gráfico",
  "Arquiteto",
  "Contador",
  "Enfermeiro",
  "Psicólogo",
  "Dentista",
  "Farmacêutico",
  "Jornalista",
  "Publicitário",
  "Bancário",
  "Guia de Turismo",
  "Administrador",
  "Economista",
  "Engenheiro Civil",
  "Engenheiro Mecânico",
  "Eletricista",
  "Técnico em Informática",
  "Programador",
  "Atleta",
  "Palhaço",
  "YouTuber",
  "Influencer",
  "Músico",
  "Ator",
  "Dublador",
  "Fotógrafo",
  "Dublê",
  "Redator",
  "Tradutor",
  "Astrônomo",
  "Cozinheiro",
  "Fazendeiro",
  "Pedreiro",
  "Escritor",
  "Veterinário",
  "Biólogo",
  "Físico",
  "Matemático",
  "Arqueólogo",
  "Filósofo",
  "Bibliotecário",
  "Secretário",
  "Faxineiro",
  "Jardineiro",
  "Apresentador de TV",
  "Empresário",
  "Policial",
  "Traficante",
  "Ladrão",
  "Costureiro",
  "Cabeleireiro",
  "Motorista",
  "Enfermeiro",
  "Fisioterapeuta",
  "Nutricionista",
  "Limpador de piscina",
  "Flanelinha",
  "Estilista",
  "Caixa de mercado",
  "Editor de vídeo",
  "Pintor",
  "Bombeiro",
  "Astronauta",
  "Humorista",
  "Encanador"
];

const lugares=[
    "Gramado",
    "Foz do Iguaçu",
    "Aeroporto",
    "Shopping Center",
    "Supermercado",
    "Hospital",
    "Escola",
    "Universidade",
    "Biblioteca",
    "Parque",
    "Praia",
    "Museu",
    "Teatro",
    "Cinema",
    "Restaurante",
    "Cafeteria",
    "Hotel",
    "Pousada",
    "Estádio",
    "Academia",
    "Clínica Psiquiátrica",
    "Farmácia",
    "Posto de Gasolina",
    "Rodoviária",
    "Ônibus",
    "Cassino",
    "Torre Eiffel",
    "Pirâmide do Egito",
    "Praia",
    "Piscina",
    "Baile de formatura",
    "Jornal Nacional",
    "Nova York",
    "Torre de Prisa",
    "Academia",
    "Balada",
    "Campeonato de Vôlei",
    "Cruzeiro",
    "Acampamento",
    "Deserto",
    "Banco",
    "Centro Militar",
    "Meu quarto",
    "Cozinha",
    "Garagem",
    "Armário",
    "Sótão",
    "Porão",
    "Inferno",
    "Céu",
    "Cristo Redentor",
    "Castelo Medieval",
    "Final Copa do Mundo",
    "Cabaré",
    "Fábrica de Refrigerante",
    "Sorveteria",
    "Loja de Roupa chique",
    "Mecânico",
    "Empresa grande",
    "Show do Silvio Santos",
    "Fazenda",
    "BBB",
    "Estação de Metrô"
]

const animais = [
    "Cachorro",
    "Gato",
    "Cavalo",
    "Vaca",
    "Porco",
    "Ovelha",
    "Cabra",
    "Galinha",
    "Pato",
    "Ganso",
    "Coelho",
    "Rato",
    "Hamster",
    "Tartaruga",
    "Cobra",
    "Lagarto",
    "Sapo",
    "Rã",
    "Peixe",
    "Tubarão",
    "Golfinho",
    "Baleia",
    "Polvo",
    "Caranguejo",
    "Lagosta",
    "Águia",
    "Falcão",
    "Coruja",
    "Leão",
    "Elefante",
    "Hipopótamo",
    "Ornitorrinco",
    "Mosca",
    "Pernilongo",
    "Joaninha",
    "Gafanhoto",
    "Macaco",
    "Papagaio",
    "Periquito",
    "Beija-flor",
    "Baiacu",
    "Esquilo",
    "Arara Azul",
    "Gorila",
    "Tamanduá",
    "Lobo Guará",
    "Alce",
    "Panda",
    "Urso Polar",
    "Penguim",
    "Hiena",
    "Girafa",
    "Flamingo",
    "Urubu",
    "Raposa",
    "Urso Pardo",
    "Abelha",
    "Burro",
    "Lhama",
    "Camelo",
    "Zebra",
    "Veado",
    "Tatu",
    "Touro",
    "Leopardo",
    "Avestruz",
    "Jacaré",
    "Canguru",
    "Koala",
    "Rinoceronte",
    "Tucano",
    "Lagartixa",
    "Guaxinim",
    "Tigre",
    "Anta",
    "Onça",
    "Capivara",
    "Peixe-espada",
    "Peixe-pallhaço",
    "Piranha",
    "Candiru",
    "Orca",
    "Leão Marinho",
    "Cavalo Marinho",
    "Lagosta",
    "Camarão",
    "Plâncton",
    "Planária",
    "Babuíno",
    "Camaleão",
    "Ácaro",
    "Aranha",
    "Borboleta",
    "Besouro",
    "Mariposa",
    "Barata",
    "Formiga",
    "Polvo",
    "Lula",
    "Estrela-do-mar",
    "Ouriço-do-mar",
    "Água Viva",
    "Foca",
    "Esponja-do-mar"
]

const objetos = [
  "Lanterna",
  "Lápis",
  "Caneta",
  "Caderno",
  "Livro",
  "Carregador",
  "Celular",
  "Notebook",
  "Mouse",
  "Teclado",
  "Fone de Ouvido",
  "Relógio",
  "Óculos",
  "Carteira",
  "Chave",
  "Mochila",
  "Casaco",
  "Camiseta",
  "Calça",
  "Tênis",
  "Garrafa",
  "Copo",
  "Prato",
  "Garfo",
  "Panela",
  "Escova de Dentes",
  "Pente",
  "Toalha",
  "Travesseiro",
  "Cobertor",
  "Bobbie Goods",
  "Quadro de Giz",
  "Jogo de Tabuleiro",
  "Protetor Solar",
  "Bola de Vôlei",
  "Faca",
  "Palito de Dente",
  "Xampu",
  "Condicionador",
  "Pendrive",
  "Carro",
  "HB20",
  "Controle Remoto",
  "Televisão",
  "Ventilador",
  "Ar-Condicionado",
  "Micro-ondas",
  "Geladeira",
  "Fogão",
  "Liquidificador",
  "Aspirador de Pó",
  "Cafeteira",
  "Cadeira",
  "Mesa",
  "Sofá",
  "Luminária",
  "Espelho",
  "Tapete",
  "Cortina",
  "Quadro",
  "Extensão Elétrica",
  "Adaptador de Tomada",
  "Power Bank",
  "Caixa de Som",
  "Impressora",
  "Câmera",
  "Tripé",
  "Capacete",
  "Guarda-chuva",
  "Mala",
  "Bicicleta",
  "Patinete",
  "Fotografia",
  "Câmera",
  "Impressora 3D",
  "Pá",
  "Machado",
  "Enxada",
  "Foice",
  "Correntes",
  "Coleira",
  "Meia",
  "Remédio",
  "Vaso",
  "Tupperware",
  "Cueca",
  "Cabide",
  "Varal",
  "Agulha",
  "Calendário",
  "CD",
  "Anel",
  "Boia",
  "Cama",
  "Dado",
  "Iate",
  "Mapa",
  "Mola",
  "Pano",
  "Rede",
  "Saia",
  "Baú",
  "Ímã",
  "Álbum",
  "Bomba",
  "Broca",
  "Colar",
  "Jarra",
  "Jornal",
  "Pijama",
  "Tapete",
  "Violão",
  "Xícara",
  "Flauta",
  "Estojo",
  "Beliche",
  "Bússola",
  "Bengala",
  "Diário",
  "Esponja",
  "Foguete",
  "Asa Delta",
  "Avião",
  "Terno",
  "Panfleto"
]

const pessoas = [
    "Elon Musk",
    "Virgínia",
    "Vini jr",
    "Neymar",
    "Lula",
    "Bolsonaro",
    "Enaldinho",
    "Taylor Swift",
    "Michael Jackson",
    "Anitta",
    "Whindersson Nunes",
    "Silvio Santos",
    "Rodrigo Faro",
    "Luciano Huck",
    "Pedro",
    "João",
    "Augusto",
    "Davi",
    "Dayan",
    "Gabriel",
    "Flavio",
    "Marcelo",
    "Henrique",
    "Bruno Mars",
    "Justin Bieber"
    ]

const clash = [
  
]


var palavra

function comecar(){
    let oxente = document.getElementById("tema").value
    if (oxente == "prof"){
        jogar(prof)
    }
    else if(oxente == "lugares"){
        jogar(lugares)
    }
    else if(oxente == "animais"){
        jogar(animais)
    }
    else if(oxente == "pessoas"){
        jogar(pessoas)
    }
    else if(oxente == "objetos"){
        jogar(objetos)
    }
    else if(oxente =="clash"){
        jogar(clash)
    }
}

function jogar(arr){
    palavra = arr[Math.floor(Math.random()*arr.length)]
    let nu = document.getElementById("num").value
    let imposter = Math.floor(Math.random()*nu)
    for(let i = 0 ; i <nu; i++){
        if(i==imposter){
            document.getElementById("jogo").innerHTML += `<button onclick="imposter(${i+1})" id="${i+1}">${i+1}</button>`
        }
        else{
            document.getElementById("jogo").innerHTML += `<button onclick="mostrar(${i+1})" id="${i+1}">${i+1}</button>`
        }
    }
}

function imposter(indice){
    document.getElementById("result").textContent = "IMPOSTOR!"
    document.getElementById(indice).remove()
}
function mostrar(indice){
    document.getElementById("result").textContent = palavra
    document.getElementById(indice).remove()
}
function ocultar(){
    document.getElementById("result").textContent = ""

}
