const prof = [
  "Engenheiro de Software",
  "Médico",
  "Advogado",
  "Professor",
  "Designer Gráfico",
  "Arquiteto",
  "Contador",
  "Enfermeiro",
  "Psicólogo",
  "Dentista",
  "Farmacêutico",
  "Jornalista",
  "Publicitário",
  "Bancário",
  "Guia de Turismo",
  "Administrador",
  "Economista",
  "Engenheiro Civil",
  "Engenheiro Mecânico",
  "Eletricista",
  "Técnico em Informática",
  "Programador",
  "Atleta",
  "Palhaço",
  "YouTuber",
  "Influencer",
  "Músico",
  "Ator",
  "Dublador",
  "Social Media",
  "Fotógrafo",
  "Dublê",
  "Redator",
  "Tradutor",
  "Astrônomo",
  "Cozinheiro",
  "Fazendeiro",
  "Pedreiro",
  "Escritor",
  "Veterinário",
  "Biólogo",
  "Físico",
  "Matemático",
  "Arqueólogo",
  "Filósofo",
  "Bibliotecário",
  "Secretário",
  "Faxineiro",
  "Jardineiro",
  "Apresentador de TV",
  "Empresário",
  "Policial",
  "Traficante",
  "Ladrão",
  "Costureiro",
  "Cabeleireiro",
  "Motorista",
  "Enfermeiro",
  "Fisioterapeuta",
  "Nutricionista",
  "Relações Internacionais"
];

const lugares=[
    "Gramado",
    "Foz do Iguaçu",
    "Aeroporto",
    "Shopping Center",
    "Supermercado",
    "Hospital",
    "Escola",
    "Universidade",
    "Biblioteca",
    "Parque",
    "Praia",
    "Museu",
    "Teatro",
    "Cinema",
    "Restaurante",
    "Cafeteria",
    "Hotel",
    "Pousada",
    "Estádio",
    "Academia",
    "Clínica Psiquiátrica",
    "Farmácia",
    "Posto de Gasolina",
    "Rodoviária",
    "Ônibus",
    "Cassino",
    "Torre Eiffel",
    "Pirâmide do Egito",
    "Praia",
    "Piscina",
    "Baile de formatura",
    "Jornal Nacional",
    "Nova York",
    "Torre de Prisa",
    "Academia",
    "Balada",
    "Campeonato de Vôlei",
    "Cruzeiro",
    "Acampamento",
    "Deserto",
    "Banco",
    "Centro Militar"
]

const animais = [
    "Cachorro",
    "Gato",
    "Cavalo",
    "Vaca",
    "Porco",
    "Ovelha",
    "Cabra",
    "Galinha",
    "Pato",
    "Ganso",
    "Coelho",
    "Rato",
    "Hamster",
    "Tartaruga",
    "Cobra",
    "Lagarto",
    "Sapo",
    "Rã",
    "Peixe",
    "Tubarão",
    "Golfinho",
    "Baleia",
    "Polvo",
    "Caranguejo",
    "Lagosta",
    "Águia",
    "Falcão",
    "Coruja",
    "Leão",
    "Elefante"
]

const objetos = [
  "Lanterna",
  "Lápis",
  "Caneta",
  "Caderno",
  "Livro",
  "Carregador",
  "Celular",
  "Notebook",
  "Mouse",
  "Teclado",
  "Fone de Ouvido",
  "Relógio",
  "Óculos",
  "Carteira",
  "Chave",
  "Mochila",
  "Casaco",
  "Camiseta",
  "Calça",
  "Tênis",
  "Garrafa",
  "Copo",
  "Prato",
  "Garfo",
  "Panela",
  "Escova de Dentes",
  "Pente",
  "Toalha",
  "Travesseiro",
  "Cobertor",
  "Bobbie Goods",
  "Quadro de Giz",
  "Jogo de Tabuleiro",
  "Protetor Solar",
  "Bola de Vôlei",
  "Faca",
  "Palito de Dente",
  "Xampu",
  "Condicionador",
  "Pendrive",
  "Carro",
  "HB20"
];

const pessoas = [
    "Maitê Nobre",
    "Anderson Nobre jr",
    "Maísa Miyazaki",
    "Henry Miyazaki Nobre",
    "Elon Musk",
    "Virgínia",
    "Vini jr",
    "Neymar",
    "Lula",
    "Bolsonaro",
    "Enaldinho",
    "Taylor Swift",
    "Michael Jackson",
    "Anitta",
    "Whindersson Nunes",
    "Silvio Santos",
    "Rodrigo Faro",
    "Luciano Huck"
]

var palavra

function jogar(arr){
    palavra = arr[Math.floor(Math.random()*arr.length)]
    let nu = document.getElementById("num").value
    let imposter = Math.floor(Math.random()*nu)
    for(let i = 0 ; i <nu; i++){
        if(i==imposter){
            document.getElementById("jogo").innerHTML += `<button onclick="imposter()" id="${i+1}">${i+1}</button>`
        }
        else{
            document.getElementById("jogo").innerHTML += `<button onclick="mostrar()" id="${i+1}">${i+1}</button>`
        }
    }
}

function imposter(){
    document.getElementById("result").textContent = "IMPOSTOR!"
}
function mostrar(){
    document.getElementById("result").textContent = palavra
}
function ocultar(){
    document.getElementById("result").textContent = ""
}