const clash = [
  "Gigante",
  "Mosqueteira",
  "Cavaleiro",
  "Mini P.E.K.K.A",
  "Tesla",
  "Exército de Esqueletos",
  "Golem",
  "Príncipe",
  "Mago",
  "Bebê Dragão",
  "Barril de Goblins",
  "Recrutas Reais",
  "Horda de Servos",
  "Cemitério",
  "Zap",
  "Bandida Líder",
  "Cavaleiro Dourado",
  "Rei Esqueleto",
  "Sparky",
  "Bruxa Mãe",
  "Golem de Elixir",
  "Três Mosqueteiras",
  "Gigante das Runas",
  "Vácuo",
  "Encomenda Real",
  "Goblins",
  "Mineiro",
  "O Tronco",
  "Arqueiras",
  "Goblin Gigante",
  "Executor",
  "Espelho",
  "Valquíria",
  "Gigante Real",
  "Fornalha",
  "Pirotécnica",
  "Lançador",
  "Balão",
  "Golem de Gelo",
  "Servos",
  "Foguete",
  "Jaula de Goblin",
  "Porcos Reais",
  "X-Besta",
  "Fúria",
  "Tesla",
  "Aríete de Batalha",
  "Barril de Esqueletos",
  "Cabana de Goblins",
  "Terremoto",
  "Dragão Elétrico",
  "Caçador",
  "Morteiro",
  "Espírito Elétrico",
  "Canhão",
  "Espírito de Gelo",
  "Lápide",
  "Veneno",
  "Bola de Fogo",
  "Megacavaleiro",
  "Máquina Goblin",
  "Domadora de Carneiro",
  "Bruxa Sombria",
  "Lenhador",
  "Arqueiro Mágico",
  "Fênix",
  "Pescador",
  "Princesa",
  "Espírito de Fogo",
  "Coletor de Elixir",
  "Cabana de Bárbaros",
  "Patifes",
  "Berserker",
  "Flechas",
  "Clone",
  "Tornado",
  "Bárbaros",
  "Bola de Neve",
  "Curadora Guerreira",
  "Príncipe das Trevas",
  "Eletrocutadores",
  "Torre de Bombas",
  "Bárbaros de Elite",
  "Escavadeira de Goblins",
  "Esqueletos",
  "Goblins Lanceiros",
  "Bombardeiro",
  "P.E.K.K.A",
  "Megaservo",
  "Espírito Curador",
  "Arbusto Traiçoeiro",
  "Morcegos",
  "Relâmpago",
  "Esqueleto Gigante",
  "Gelo",
  "Gigante Elétrico",
  "Vinhas",
  "Maldição Goblin",
  "Goblin com Dardo",
  "Dragões Esqueleto",
  "Máquina Voadora",
  "Carrinho de Canhão",
  "Bruxa",
  "Guardas",
  "Barril de Bárbaro",
  "Corredor",
  "Goblin Demolidor",
  "Dragão Infernal",
  "Mago de Gelo",
  "Destruidores de Muro",
  "Gangue de Goblins"
]