const lugares=[
    "Gramado",
    "Foz do Iguaçu",
    "Aeroporto",
    "Shopping Center",
    "Supermercado",
    "Hospital",
    "Escola",
    "Universidade",
    "Biblioteca",
    "Parque",
    "Praia",
    "Museu",
    "Teatro",
    "Cinema",
    "Restaurante",
    "Cafeteria",
    "Hotel",
    "Pousada",
    "Estádio",
    "Academia",
    "Clínica Psiquiátrica",
    "Farmácia",
    "Posto de Gasolina",
    "Rodoviária",
    "Ônibus",
    "Cassino",
    "Torre Eiffel",
    "Pirâmide do Egito",
    "Praia",
    "Piscina",
    "Baile de formatura",
    "Jornal Nacional",
    "Nova York",
    "Torre de Prisa",
    "Academia",
    "Balada",
    "Campeonato de Vôlei",
    "Cruzeiro",
    "Acampamento",
    "Deserto",
    "Banco",
    "Centro Militar",
    "Meu quarto",
    "Cozinha",
    "Garagem",
    "Armário",
    "Sótão",
    "Porão",
    "Inferno",
    "Céu",
    "Cristo Redentor",
    "Castelo Medieval",
    "Final Copa do Mundo",
    "Cabaré",
    "Fábrica de Refrigerante",
    "Sorveteria",
    "Loja de Roupa chique",
    "Mecânico",
    "Empresa grande",
    "Show do Silvio Santos",
    "Fazenda",
    "BBB",
    "Estação de Metrô"
]