const mine2 = [
    "Pá",
    "Picareta",
    "Machado",
    "Enxada",
    "Balde",
    "Água",
    "Lava",
    "Neve",
    "Neve Fofa",
    "Leite",
    "Vara de Pesca",
    "Pederneira",
    "Bola de Fogo",
    "Farinha de Osso",
    "Tesoura",
    "Name Tag",
    "Laço",
    "Bússola",
    "Relógio",
    "Luneta",
    "Mapa",
    "Livro e Pena",
    "Projétil de Vento",
    "Ender Pearl",
    "Olho do Fim",
    "Elytra",
    "Foguete",
    "Sela",
    "Barco",
    "Barco com Baú",
    "Trilho",
    "Trilho Elétrico",
    "Carrinho",
    "Carrinho com Funil",
    "Carrinho com Baú",
    "Carrinho com Fornalha",
    "Carrinho com TNT",
    "Disco",
    "Espada",
    "Tridente",
    "Mace",
    "Escudo",
    "Capacete",
    "Peitoral",
    "Calça",
    "Bota",
    "Armadura de Cavalo",
    "Armadura de Cachorro",
    "Totem da Imortalidade",
    "TNT",
    "Cristal do End",
    "Bola de Neve",
    "Ovo",
    "Arco",
    "Besta",
    "Flecha",
    "Maçã",
    "Maçã Dourada",
    "Melancia",
    "Bagas Doce",
    "Fruta de Coro",
    "Cenoura",
    "Cenoura Dourada",
    "Batata",
    "Beterraba",
    "Carne",
    "Peixe",
    "Baiacu",
    "Pão",
    "Biscoito",
    "Bolo",
    "Torta",
    "Carne Podre",
    "Olho de Aranha",
    "Sopa",
    "Poção",
    "Carvão",
    "Cobre",
    "Ferro",
    "Ouro",
    "Esmeralda",
    "Lápis Lazuli",
    "Diamante",
    "Netherite",
    "Quartzo",
    "Ametista",
    "Graveto",
    "Sílex",
    "Trigo",
    "Osso",
    "Linha",
    "Pena",
    "Couro",
    "Mel",
    "Bolsa de Tinta",
    "Slime",
    "Varinha de Blaze",
    "Corante Branco",
    "Corante Cinza",
    "Corante Preto",
    "Corante Marrom",
    "Corante Vermelho",
    "Corante Laranja",
    "Corante Amarelo",
    "Corante Verde-Limão",
    "Corante Verde",
    "Corante Ciano",
    "Corante Azul-Claro",
    "Corante Azul",
    "Corante Roxo",
    "Corante Magenta",
    "Corante Rosa",
    "Tijolo",
    "Papel",
    "Livro",
    "Frasco de Vidro",
    "Fungo do Nether",
    "Redstone",
    "Glowstone",
    "Pólvora",
    "Açúcar",
    "Frasco de XP",
    "Livro Encantado",
    "Spawner",
    "Allay",
    "Tatu",
    "Axolote",
    "Morcego",
    "Abelha",
    "Blaze",
    "Camelo",
    "Gato",
    "Aranha Venenosa",
    "Galinha",
    "Golem de Cobre",
    "Vaca",
    "Creeper",
    "Golfinho",
    "Burro",
    "Guardian",
    "Enderman",
    "Endermite",
    "Raposa",
    "Sapo",
    "Ghast",
    "Lula",
    "Cabra",
    "Hoglin",
    "Cavalo",
    "Golem de Ferro",
    "Lhama",
    "Magma Cube",
    "Vaca Cogumelo",
    "Jaguatirica",
    "Panda",
    "Papagaio",
    "Phanton",
    "Ovelha",
    "Shulker",
    "Silver Fish",
    "Esqueleto",
    "Slime",
    "Golem de Neve",
    "Aranha",
    "Tartaruga",
    "Vex",
    "Villager",
    "Vingador",
    "Warden",
    "Bruxa",
    "Wither Skeleton",
    "Lobo",
    "Zumbi",
    "Piglin",
    "Zombie Piglin",
    "Porco",
    "Urso Polar",
    "Coelho",
    "Tronco de Madeira",
    "Tábuas de Madeira",
    "Cerca",
    "Portão",
    "Porta",
    "Trapdoor",
    "Placa de Pressão",
    "Botão",
    "Pedra",
    "Pedregulho",
    "Pedra Lisa",
    "Granito",
    "Diorito",
    "Andesito",
    "Deepslate",
    "Arenito",
    "Lanterna Marinha",
    "Netherrack",
    "Muro",
    "Basalto",
    "Pedra Negra",
    "Pedra do End",
    "Corrente",
    "Bloco de Carvão",
    "Bloco de Ferro",
    "Bloco de Ouro",
    "Bloco de Redstone",
    "Bloco de Esmeralda",
    "Bloco de Lápis Lazuli",
    "Bloco de Diamante",
    "Bloco de Netherite",
    "Bloco de Ametista",
    "Bloco de Quartzo",
    "Bloco de Cobre",
    "Lã",
    "Carpete",
    "Terracota",
    "Concreto",
    "Cimento",
    "Azulejo",
    "Vidro",
    "Painel de Vidro",
    "Caixa de Shulker",
    "Cama",
    "Vela",
    "Banner",
    "Bloco de Grama",
    "Terra",
    "Lama",
    "Argila",
    "Gravel",
    "Areia",
    "Gelo",
    "Bloco de Musgo",
    "Estalactite",
    "Bloco de Magma",
    "Obsidian",
    "Soul Sand",
    "Bloco de Osso",
    "Folhas",
    "Sapling",
    "Cogumelo",
    "Flor",
    "Bambu",
    "Cana",
    "Cacto",
    "Vitória-Régia",
    "Vinhas",
    "Alga",
    "Pepino do Mar",
    "Esponja",
    "Abóbora",
    "Bloco de Feno",
    "Colmeia",
    "Teia",
    "Bedrock",
    "Tocha",
    "Lampião",
    "Lâmpada de Redstone",
    "Crafting Table",
    "Stone Cutter",
    "Bancada de Cartografia",
    "Bancada de Arco e Flecha",
    "Smithing Table",
    "Tear",
    "Fornalha",
    "Fogueira",
    "Bigorna",
    "Composteira",
    "Toca disco",
    "Bloco Musical",
    "Mesa de Encantamento",
    "Suporte de Poções",
    "Caldeirão",
    "Sino",
    "Andaime",
    "Para-Raios",
    "Vaso",
    "Armor Stand",
    "Item Frame",
    "Quadro",
    "Estante de Livro",
    "Estante",
    "Placa",
    "Baú",
    "Barril",
    "Ender Chest",
    "Cabeças",
    "Portal do End",
    "Repetidor",
    "Comparador",
    "Alavanca",
    "Detector de Luz Solar",
    "Pistão",
    "Pistão com Slime",
    "Dispenser",
    "Dropper",
    "Carfter",
    "Funil",
    "Observer",
    "Ender Dragon",
    "Wither",
    "Vila",
    "Trial Chamber",
    "Ancient City",
    "End City",
    "Ocean Temple",
    "Mineshaft",
    "Piramide do Deserto",
    "Ruined Portal",
    "Barco Afundado",
    "Stronghold",
    "Posto Pillager",
    "Mansão",
    "Igloo",
    "Jungle Temple",
    "Ocean Monument",
    "Fortaleza do Nether",
    "Bastion",
    "Lectern",
    "Beacon",
    "Grindstone",
    "Breeze"
]