const objetos = [
  "Lanterna",
  "Lápis",
  "Caneta",
  "Caderno",
  "Livro",
  "Carregador",
  "Celular",
  "Notebook",
  "Mouse",
  "Teclado",
  "Fone de Ouvido",
  "Relógio",
  "Óculos",
  "Carteira",
  "Chave",
  "Mochila",
  "Casaco",
  "Camiseta",
  "Calça",
  "Tênis",
  "Garrafa",
  "Copo",
  "Prato",
  "Garfo",
  "Panela",
  "Escova de Dentes",
  "Pente",
  "Toalha",
  "Travesseiro",
  "Cobertor",
  "Bobbie Goods",
  "Quadro de Giz",
  "Jogo de Tabuleiro",
  "Protetor Solar",
  "Bola de Vôlei",
  "Faca",
  "Palito de Dente",
  "Xampu",
  "Condicionador",
  "Pendrive",
  "Carro",
  "HB20",
  "Controle Remoto",
  "Televisão",
  "Ventilador",
  "Ar-Condicionado",
  "Micro-ondas",
  "Geladeira",
  "Fogão",
  "Liquidificador",
  "Aspirador de Pó",
  "Cafeteira",
  "Cadeira",
  "Mesa",
  "Sofá",
  "Luminária",
  "Espelho",
  "Tapete",
  "Cortina",
  "Quadro",
  "Extensão Elétrica",
  "Adaptador de Tomada",
  "Power Bank",
  "Caixa de Som",
  "Impressora",
  "Câmera",
  "Tripé",
  "Capacete",
  "Guarda-chuva",
  "Mala",
  "Bicicleta",
  "Patinete",
  "Fotografia",
  "Câmera",
  "Impressora 3D",
  "Pá",
  "Machado",
  "Enxada",
  "Foice",
  "Correntes",
  "Coleira",
  "Meia",
  "Remédio",
  "Vaso",
  "Tupperware",
  "Cueca",
  "Cabide",
  "Varal",
  "Agulha",
  "Calendário",
  "CD",
  "Anel",
  "Boia",
  "Cama",
  "Dado",
  "Iate",
  "Mapa",
  "Mola",
  "Pano",
  "Rede",
  "Saia",
  "Baú",
  "Ímã",
  "Álbum",
  "Bomba",
  "Broca",
  "Colar",
  "Jarra",
  "Jornal",
  "Pijama",
  "Tapete",
  "Violão",
  "Xícara",
  "Flauta",
  "Estojo",
  "Beliche",
  "Bússola",
  "Bengala",
  "Diário",
  "Esponja",
  "Foguete",
  "Asa Delta",
  "Avião",
  "Terno",
  "Panfleto"
]