const pessoas = [
    "Elon Musk",
    "Virgínia",
    "Vini jr",
    "Neymar",
    "Lula",
    "Bolsonaro",
    "Enaldinho",
    "Taylor Swift",
    "Michael Jackson",
    "Anitta",
    "Whindersson Nunes",
    "Silvio Santos",
    "Rodrigo Faro",
    "Luciano Huck",
    "Pedro",
    "João",
    "Augusto",
    "Davi",
    "Dayan",
    "Gabriel",
    "Flavio",
    "Marcelo",
    "Henrique",
    "Bruno Mars",
    "Justin Bieber"
];
