const prof = [
  "Engenheiro de Software",
  "Médico",
  "Advogado",
  "Professor",
  "Designer Gráfico",
  "Arquiteto",
  "Contador",
  "Enfermeiro",
  "Psicólogo",
  "Dentista",
  "Farmacêutico",
  "Jornalista",
  "Publicitário",
  "Bancário",
  "Guia de Turismo",
  "Administrador",
  "Economista",
  "Engenheiro Civil",
  "Engenheiro Mecânico",
  "Eletricista",
  "Técnico em Informática",
  "Programador",
  "Atleta",
  "Palhaço",
  "YouTuber",
  "Influencer",
  "Músico",
  "Ator",
  "Dublador",
  "Fotógrafo",
  "Dublê",
  "Redator",
  "Tradutor",
  "Astrônomo",
  "Cozinheiro",
  "Fazendeiro",
  "Pedreiro",
  "Escritor",
  "Veterinário",
  "Biólogo",
  "Físico",
  "Matemático",
  "Arqueólogo",
  "Filósofo",
  "Bibliotecário",
  "Secretário",
  "Faxineiro",
  "Jardineiro",
  "Apresentador de TV",
  "Empresário",
  "Policial",
  "Traficante",
  "Ladrão",
  "Costureiro",
  "Cabeleireiro",
  "Motorista",
  "Enfermeiro",
  "Fisioterapeuta",
  "Nutricionista",
  "Limpador de piscina",
  "Flanelinha",
  "Estilista",
  "Caixa de mercado",
  "Editor de vídeo",
  "Pintor",
  "Bombeiro",
  "Astronauta",
  "Humorista",
  "Encanador"
];