const animes = [
    "Saitama (One Punch Man)",
    "Genos (One Punch Man)",
    "Goku (Dragon Ball)",
    "Vegeta (Dragon Ball)",
    "Gohan (Dragon Ball)",
    "Piccolo (Dragon Ball)",
    "Kuririn (Dragon Ball)",
    "Chi Chi (Dragon Ball)",
    "Bulma (Dragon Ball)",
    "Shenlong (Dragon Ball)",
    "Majin Boo (Dragon Ball)",
    "Freeza (Dragon Ball)",
    "Naruto (Naruto)",
    "Sasuke (Naruto)",
    "Sakura (Naruto)",
    "Kakashi (Naruto)",
    "Minato (Naruto)",
    "Itachi (Naruto)",
    "Madara (Naruto)",
    "Obito (Naruto)",
    "Jotaro (JOJO)",
    "Dio (JOJO)",
    "Deku (Boku no Hero)",
    "Seya (Cavaleiros do Zodíaco)",
    "Pikachu (Pokemon)",
    "Ash (Pokemon)",
    "Meliodas (Nanatsu no Taizai)",
    "Escanor (Nanatsu no Taizai)",
    "Luffy (One Piece)",
    "Zoro (One Piece)",
    "Sanji (One Piece)",
    "L (Death Note)",
    "Light (Death Note)",
    "Gojo (Jujutsu Kaisen)",
    "Tanjiro (Demon Slayer)",
    "Nezuko (Demon Slayer)",
    "Muzan (Demon Slayer)",
    "Zenitsu (Demon Slayer)",
    "Inosuke (Demon Slayer)"
]