const desenhos = [
    "Bob Esponja (Bob Esponja)",
    "Patrick (Bob Esponja)",
    "Plankton (Bob Esponja)",
    "Seu Siriguejo (Bob Esponja)",
    "Lula Molusco (Bob Esponja)",
    "Sandy (Bob Esponja)",
    "Gary (Bob Esponja)",
    "Karen (Bob Esponja)",
    "Homem Sereia (Bob Esponja)",
    "Larry (Bob Esponja)",
    "Sra. Puff (Bob Esponja)",
    "Pérola (Bob Esponja)",
    "Timmy Turner (Os Padrinhos Mágicos)",
    "Poof (Os Padrinhos Mágicos)",
    "Wanda (Os Padrinhos Mágicos)",
    "Vicky (Os Padrinhos Mágicos)",
    "Professor Crocker (Os Padrinhos Mágicos)",
    "Mickey (Disney)",
    "Pateta (Disney)",
    "Pato Donald (Disney)",
    "Tio Patinhas (Disney)",
    "Tico (Disney)",
    "Teco (Disney)",
    "Minnie (Disney)",
    "Pluto (Disney)",
    "Finn (Hora de Aventura)",
    "Jake (Hora de Aventura)",
    "Marceline (Hora de Aventura)",
    "BMO (Hora de Aventura)",
    "Rei Gelado (Hora de Aventura)",
    "Simon (Hora de Aventura)",
    "Princesa Jujuba (Hora de Aventura)",
    "Lemon Grab (Hora de Aventura)",
    "Princesa de Fogo (Hora de Aventura)",
    "Prismo (Hora de Aventura)",
    "Princesa Caroço (Hora de Aventura)",
    "Lich (Hora de Aventura)",
    "Mordomo Menta (Hora de Aventura)",
    "Canelinha (Hora de Aventura)",
    "Lady Íris (Hora de Aventura)",
    "Fern (Hora de Aventura)",
    "Billy (Hora de Aventura)",
    "Cake (Hora de Aventura)",
    "Fiona (Hora de Aventura)",
    "Guarda Banana (Hora de Aventura)",
    "Gunther (Hora de Aventura)",
    "Sra. Tromba (Hora de Aventura)",
    "Pernalonga (Looney Tunes)",
    "Patolino (Looney Tunes)",
    "Piu Piu (Looney Tunes)",
    "Frajola (Looney Tunes)",
    "Gaguinho (Looney Tunes)",
    "Coiote (Looney Tunes)",
    "Marvin Marciano (Looney Tunes)",
    "Lola Bunny (Looney Tunes)",
    "Taz (Looney Tunes)",
    "Papaléguas (Looney Tunes)",
    "Homer (Os Simpsons)",
    "Marge (Os Simpsons)",
    "Bart (Os Simpsons)",
    "Lisa (Os Simpsons)",
    "Maggie (Os Simpsons)",
    "Lindinha (Meninas Superpoderosas)",
    "Florzinho (Meninas Superpoderosas)",
    "Docinho (Meninas Superpoderosas)",
    "Macaco Louco (Meninas Superpoderosas)",
    "Ele (Meninas Superpoderosas)",
    "Professor (Meninas Superpoderosas)",
    "Pica-Pau (Pica-Pau)",
    "Zeca Urubu (Pica-Pau)",
    "Leôncio (Pica-Pau)",
    "Mônica (Turma da Mônica)",
    "Cebolinha (Turma da Mônica)",
    "Magali (Turma da Mônica)",
    "Cascão (Turma da Mônica)",
    "Chico Bento (Turma da Mônica)",
    "Irmão do Jorel (Cartoon Network)",
    "Coragem (Cartoon Network)",
    "Johnny Bravo (Cartoon Network)",
    "Dexter (Cartoon Network)",
    "Chowder (Cartoon Network)",
    "Puro Osso (Cartoon Network)",
    "Billy (Cartoon Network)",
    "Mandy (Cartoon Network)",
    "Flapjack (Cartoon Network)",
    "Gumball (O Incrível Mundo de Gumball)",
    "Darwin (O Incrível Mundo de Gumball)",
    "Ricardo (O Incrível Mundo de Gumball)",
    "Nicole (O Incrível Mundo de Gumball)",
    "Anais (O Incrível Mundo de Gumball)",
    "Larry (O Incrível Mundo de Gumball)",
    "Vô Max (Ben 10)",
    "Ben 10 (Ben 10)",
    "Gwen (Ben 10)",
    "Kevin (Ben 10)",
    "Vilgax (Ben 10)",
    "Tom (Tom e Jerry)",
    "Jerry (Tom e Jerry)",
    "Salsicha (Scooby Doo)",
    "Scooby Doo (Scooby Doo)",
    "Velma (Scooby Doo)",
    "Fred (Scooby Doo)",
    "Daphne (Scooby Doo)",
    "Mordecai (Apenas um Show)",
    "Rigby (Apenas um Show)",
    "Musculoso (Apenas um Show)",
    "Benson (Apenas um Show)",
    "Saltitão (Apenas um Show)",
    "Pairulito (Apenas um Show)",
    "Fantasmão (Apenas um Show)",
    "Margaret (Apenas um Show)",
    "Eileen (Apenas um Show)",
    "Thomas (Apenas um Show)",
    "C.J. (Apenas um Show)",
    "Rick (Rick and Morty)",
    "Morty (Rick and Morty)",
    "Mabel (Gravity Falls)",
    "Dipper (Gravity Falls)",
    "Wendy (Gravity Falls)",
    "Soos (Gravity Falls)",
    "Tivô Stan (Gravity Falls)",
    "Tivô Ford (Gravity Falls)",
    "Bill Cipher (Gravity Falls)",
    "Peixonauta (Peixonauta)"
]