const filmes = [
    "Shrek (Shrek)",
    "Burro (Shrek)",
    "Lorde Farquaad (Shrek)",
    "Fiona (Shrek)",
    "Dragão (Shrek)",
    "Gato de Botas (Shrek)",
    "Biscoito (Shrek)",
    "Rei Julien (Madagascar)",
    "Glória (Madagascar)",
    "Melman (Madagascar)",
    "Alex (Madagascar)",
    "Marty (Madagascar)",
    "Maurice (Madagascar)",
    "Capitão (Madagascar)",
    "Kowalski (Madagascar)",
    "Recruta (Madagascar)",
    "Rico (Madagascar)",
    "Tai Lung (Kung Fu Panda)",
    "Mestre Shifu (Kung Fu Panda)",
    "Po (Kung Fu Panda)",
    "Tigresa (Kung Fu Panda)",
    "Oogway (Kung Fu Panda)",
    "Sr. Ping (Kung Fu Panda)",
    "Louva a Deus (Kung Fu Panda)",
    "Macaco (Kung Fu Panda)",
    "Víbora (Kung Fu Panda)",
    "Garça (Kung Fu Panda)",
    "Lorde Shen (Kung Fu Panda)",
    "Kai (Kung Fu Panda)",
    "Soluço (HTTYD)",
    "Astrid (HTTYD)",
    "Stoico (HTTYD)",
    "Bocão (HTTYD)",
    "Melequento (HTTYD)",
    "Cabeça Quente (HTTYD)",
    "Perna de Peixe (HTTYD)",
    "Cabeça Dura (HTTYD)",
    "Bangela (HTTYD)",
    "Tempestade (HTTYD)",
    "Megamente (Megamente)",
    "Metro Man (Megamente)",
    "Titan (Megamente)",
    "Criado (Megamente)",
    "Buzz (Toy Story)",
    "Woody (Toy Story)",
    "Sid (Toy Story)",
    "Betty (Toy Story)",
    "Andy (Toy Story)",
    "Aliens (Toy Story)",
    "Sr. Cabeça de Batata (Toy Story)",
    "Rex (Toy Story)",
    "Slinky (Toy Story)",
    "Porquinho (Toy Story)",
    "Sra. Cabeça de Batata (Toy Story)",
    "Jessie (Toy Story)",
    "Zurg (Toy Story)",
    "Barbie (Toy Story)",
    "Lotso (Toy Story)",
    "Ken (Toy Story)",
    "O Macaco (Toy Story)",
    "Mike Wazowski (Monstros S.A.)",
    "Boo (Monstros S.A.)",
    "Randall (Monstros S.A.)",
    "Sullivan (Monstros S.A.)",
    "Nemo (Procurando Nemo)",
    "Dori (Procurando Nemo)",
    "Marlin (Procurando Nemo)",
    "Sr. Incrível (Os Incríveis)",
    "Mulher Elástica (Os Incríveis)",
    "Violeta (Os Incríveis)",
    "Flecha (Os Incríveis)",
    "Gelado (Os Incríveis)",
    "Síndrome (Os Incríveis)",
    "Edna Moda (Os Incríveis)",
    "Zezé (Os Incríveis)",
    "McQueen (Carros)",
    "Doc Hudson (Carros)",
    "Mate (Carros)",
    "Francesco Bernoulli (Carros)",
    "Jackson Storm (Carros)",
    "Remy (Ratatouille)",
    "Linguini (Ratatouille)",
    "Chefe Skinner (Ratatouille)",
    "Gusteau (Ratatouille)",
    "WALL-E (WALL-E)",
    "EVA (WALL-E)",
    "Sr. Fredricksen (UP-Altas Aventuras)",
    "Russel (UP-Altas Aventuras)",
    "Dug (UP-Altas Aventuras)",
    "Alegria (Divertidamente)",
    "Raiva (Divertidamente)",
    "Tristeza ((Divertidamente)",
    "Nojinho (Divertidamente)",
    "Medo (Divertidamente)",
    "Ralph (Detona Ralph)",
    "Vanellope (Detona Ralph)",
    "Felix (Detona Ralph)",
    "Rei Doce (Detona Ralph)",
    "Baymax (Operação Big Hero)",
    "Bolt (Bolt: Supercão)",
    "Lilo (Lilo e Stitch)",
    "Stich (Lilo e Stitch)",
    "Harry Potter (Harry Potter)",
    "Hermione (Harry Potter)",
    "Ron Weasley (Harry Potter)",
    "Voldemort (Harry Potter)",
    "Draco Malfoy (Harry Potter)",
    "Snape (Harry Potter)",
    "Hagrid (Harry Potter)",
    "Dumbledore (Harry Potter)",
    "Palpatine (Star Wars)",
    "Darth Vader (Star Wars)",
    "Chewbacca (Star Wars)",
    "R2-D2 (Star Wars)",
    "C-3PO (Star Wars)",
    "Yoda (Star Wars)",
    "Obi-Wan (Star Wars)",
    "Luke Skywalker (Star Wars)",
    "Princesa Leia (Star Wars)",
    "Han Solo (Star Wars)",
    "Grinch (O Grinch)",
    "Simba (Rei Leão)",
    "Scar (Rei Leão)",
    "Mufasa (Rei Leão)",
    "Timão (Rei Leão)",
    "Pumba (Rei Leão)",
    "Gru (Meu Malvado Favorito)",
    "Vector (Meu Malvado Favorito)",
    "Minions (Meu Malvado Favorito)",
    "El Macho (Meu Malvado Favorito)"
]