const herois = [
    "Homem de Ferro (Marvel)",
    "Capitão América (Marvel)",
    "Thor (Marvel)",
    "Hulk (Marvel)",
    "Viúva Negra (Marvel)",
    "Gavião Arqueiro (Marvel)",
    "Homem Aranha (Marvel)",
    "Wolverine (Marvel)",
    "Homem Formiga (Marvel)",
    "Falcão (Marvel)",
    "Capitã Marvel (Marvel)",
    "Besouro Azul (DC)",
    "Doutor Estranho (Marvel)",
    "Deadpool (Marvel)",
    "Pantera Negra (Marvel)",
    "Rocket (Marvel)",
    "Groot (Marvel)",
    "Senhor das Estrelas (Marvel)",
    "Drax (Marvel)",
    "Gamora (Marvel)",
    "Nebula (Marvel)",
    "Mulher Invisível (Marvel)",
    "O Coisa (Marvel)",
    "Tocha Humana (Marvel)",
    "Sr. Fantástico (Marvel)",
    "Loki (Marvel)",
    "Caveira Vermelha (Marvel)",
    "Thanos (Marvel)",
    "Soldado Invernal (Marvel)",
    "Sr. Destino (Marvel)",
    "Surfista Prateado (Marvel)",
    "Galactus (Marvel)",
    "Kraven (Marvel)",
    "Venom (Marvel)",
    "Dr. Octopus (Marvel)",
    "Duende Verde (Marvel)",
    "Electro (Marvel)",
    "Carnificina (Marvel)",
    "Professor Xavier (Marvel)",
    "Tempestade (Marvel)",
    "Magneto (Marvel)",
    "Ciclope (Marvel)",
    "Mística (Marvel)",
    "Fera (Marvel)",
    "Batman (DC)",
    "Superman (DC)",
    "Mulher Maravilha (DC)",
    "Aquaman (DC)",
    "Flash (DC)",
    "Lanterna Verde (DC)",
    "Arqueiro Verde (DC)",
    "Shazam (DC)",
    "Ciborgue (DC)",
    "Caçador de Marte (DC)",
    "Mulher Gavião (DC)",
    "SuperGirl (DC)",
    "BatGirl (DC)",
    "Robin (DC)",
    "Asa Noturna (DC)",
    "Estelar (DC)",
    "Ravena (DC)",
    "Mutano (DC)",
    "Kid Flash (DC)",
    "Coringa (DC)",
    "Charada (DC)",
    "Capitão Frio (DC)",
    "Arlequina (DC)",
    "Lex Luthor (DC)",
    "Brainiac (DC)",
    "Darkseid (DC)",
    "Pinguim (DC)",
    "Mulher Gato (DC)",
    "Espantalho (DC)",
    "Duas Caras (DC)",
    "Bane (DC)",
    "Hera Venenosa (DC)",
    "Ra's al Ghul (DC)",
    "Flash Reverso (DC)"
]